// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAKA20_DB;

#nullable disable

namespace SAKA20_DB2.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAKA20_DB.Entities.Utilisateur", b =>
                {
                    b.Property<int>("IDutilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDutilisateur"));

                    b.Property<bool>("Activated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Admin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("AdresseCodePostal")
                        .HasColumnType("int");

                    b.Property<string>("AdresseCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdresseNumero")
                        .HasColumnType("int");

                    b.Property<int>("AdresseNumeroBoite")
                        .HasColumnType("int");

                    b.Property<string>("AdresseRue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresseVille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDutilisateur");

                    b.ToTable("Utilisateur");

                    b.HasData(
                        new
                        {
                            IDutilisateur = 1,
                            Activated = false,
                            Admin = false,
                            AdresseCodePostal = 1000,
                            AdresseCountry = "Belgique",
                            AdresseNumero = 10,
                            AdresseNumeroBoite = 1,
                            AdresseRue = "Rue de la Paix",
                            AdresseVille = "Bruxelles",
                            Cancelled = false,
                            Email = "jean.dupont@example.com",
                            Nom = "Dupont",
                            Password = "password123",
                            PhoneNumber = 498123456,
                            Prenom = "Jean"
                        },
                        new
                        {
                            IDutilisateur = 2,
                            Activated = true,
                            Admin = true,
                            AdresseCodePostal = 1050,
                            AdresseCountry = "Belgique",
                            AdresseNumero = 20,
                            AdresseNumeroBoite = 2,
                            AdresseRue = "Avenue Louise",
                            AdresseVille = "Bruxelles",
                            Cancelled = false,
                            Email = "sophie.martin@example.com",
                            Nom = "Martin",
                            Password = "password123",
                            PhoneNumber = 498765432,
                            Prenom = "Sophie"
                        },
                        new
                        {
                            IDutilisateur = 3,
                            Activated = true,
                            Admin = false,
                            AdresseCodePostal = 1070,
                            AdresseCountry = "Belgique",
                            AdresseNumero = 30,
                            AdresseNumeroBoite = 3,
                            AdresseRue = "Chaussée de Mons",
                            AdresseVille = "Bruxelles",
                            Cancelled = false,
                            Email = "marie.bernard@example.com",
                            Nom = "Bernard",
                            Password = "password123",
                            PhoneNumber = 498543210,
                            Prenom = "Marie"
                        },
                        new
                        {
                            IDutilisateur = 4,
                            Activated = false,
                            Admin = false,
                            AdresseCodePostal = 1000,
                            AdresseCountry = "Belgique",
                            AdresseNumero = 40,
                            AdresseNumeroBoite = 4,
                            AdresseRue = "Rue Royale",
                            AdresseVille = "Bruxelles",
                            Cancelled = false,
                            Email = "paul.leroy@example.com",
                            Nom = "Leroy",
                            Password = "password123",
                            PhoneNumber = 498432109,
                            Prenom = "Paul"
                        },
                        new
                        {
                            IDutilisateur = 5,
                            Activated = true,
                            Admin = false,
                            AdresseCodePostal = 1000,
                            AdresseCountry = "Belgique",
                            AdresseNumero = 50,
                            AdresseNumeroBoite = 5,
                            AdresseRue = "Boulevard Anspach",
                            AdresseVille = "Bruxelles",
                            Cancelled = false,
                            Email = "julie.dupuis@example.com",
                            Nom = "Dupuis",
                            Password = "password123",
                            PhoneNumber = 498321098,
                            Prenom = "Julie"
                        },
                        new
                        {
                            IDutilisateur = 6,
                            Activated = true,
                            Admin = true,
                            AdresseCodePostal = 1050,
                            AdresseCountry = "Belgique",
                            AdresseNumero = 60,
                            AdresseNumeroBoite = 6,
                            AdresseRue = "Place du Luxembourg",
                            AdresseVille = "Bruxelles",
                            Cancelled = false,
                            Email = "pierre.moreau@example.com",
                            Nom = "Moreau",
                            Password = "password123",
                            PhoneNumber = 498210987,
                            Prenom = "Pierre"
                        },
                        new
                        {
                            IDutilisateur = 7,
                            Activated = false,
                            Admin = false,
                            AdresseCodePostal = 1040,
                            AdresseCountry = "Belgique",
                            AdresseNumero = 70,
                            AdresseNumeroBoite = 7,
                            AdresseRue = "Rue de la Loi",
                            AdresseVille = "Bruxelles",
                            Cancelled = false,
                            Email = "claire.renard@example.com",
                            Nom = "Renard",
                            Password = "password123",
                            PhoneNumber = 498109876,
                            Prenom = "Claire"
                        },
                        new
                        {
                            IDutilisateur = 8,
                            Activated = true,
                            Admin = false,
                            AdresseCodePostal = 1000,
                            AdresseCountry = "Belgique",
                            AdresseNumero = 80,
                            AdresseNumeroBoite = 8,
                            AdresseRue = "Rue des Bouchers",
                            AdresseVille = "Bruxelles",
                            Cancelled = false,
                            Email = "luc.lemoine@example.com",
                            Nom = "Lemoine",
                            Password = "password123",
                            PhoneNumber = 498098765,
                            Prenom = "Luc"
                        },
                        new
                        {
                            IDutilisateur = 9,
                            Activated = false,
                            Admin = false,
                            AdresseCodePostal = 1000,
                            AdresseCountry = "Belgique",
                            AdresseNumero = 90,
                            AdresseNumeroBoite = 9,
                            AdresseRue = "Avenue des Arts",
                            AdresseVille = "Bruxelles",
                            Cancelled = false,
                            Email = "nathalie.petit@example.com",
                            Nom = "Petit",
                            Password = "password123",
                            PhoneNumber = 497987654,
                            Prenom = "Nathalie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
